/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://kcgfovqkrwyjnjlfglvc.supabase.co"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZ2ZvdnFrcnd5am5qbGZnbHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDYwNzAsImV4cCI6MjA3NDkyMjA3MH0.gLQW6-tc6p62f2AKZQC8CO-WsoB8SfB0EztRh5-q5EY"
export const projectId = supabaseUrl.split('//')[1]?.split('.')[0] || "kcgfovqkrwyjnjlfglvc"